swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
      # - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error 
          
          
#---------------------------------New
  /user/bankaccounts/{id}:
    get:
      security: 
        - Bearer: []
      tags:
        - User Module
      summary: User Account API
      description: API to get User accounts
      parameters :
      - in: path
        name: id
        description: Login playload
        required: true
        type : string
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/BankAccountResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
          
  /user/bankaccount/{id}/transactions/:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transaction API
      description: API to get User transactions
      parameters:
        - in: path
          name: id
          description: Login payload
          required: true
          type: string
      responses:
        "200":
          description: User Transaction retrieved successfully
          schema:
            type : "array"
            items:
              $ref: "#/definitions/TransactionResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    
  /user/bankaccount/{id}/transactions/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transaction API
      description: API to get User Transactions infos
      parameters:
        - in: path
          name: id
          description: Login payload
          required: true
          type: string
      responses:
        "200":
          description: User Transaction infos retrieved successfully
          schema:
            $ref: "#/definitions/TransactionDetailsResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transaction API
      description: API to change User Transactions infos
      parameters:
        - in: path
          name: id
          description: Login payload
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/Transactions"
      responses:
        "200":
          description: User Transaction info have been successfully changed
          schema:
            $ref: "#/definitions/TransactionResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error  
#----------------------------------------------  
      
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
# ------------------------------
  Transactions:
    properties:
      category:
        type: string
      note:
        type: string
  

# -----------------------------
        
        
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
#--------------------------------------New
  BankAccountResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          amount:
            type: number
          transactionNumber:
            type: number
          balanceType:
            type: string
  TransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body: 
        type: object
        properties:
          id: 
            type: string
          date:
            type: string
            format: date-time
          description:
            type: string
          amount: 
            type: number
          balance:
            type: number
  TransactionDetailsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          category:
            type: string
          note: 
            type: string